repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        args: ["-l", "79"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8

-   repo: local
    hooks:
    -   id: check-jsonc
        name: check-jsonc
        description: 'Check JSON with comments'
        entry: python -c 'import sys, jsonc; jsonc.load(open(sys.argv[1]))'
        language: python
        types: [json]
        require_serial: true
        additional_dependencies: &jsonc
        -   "json-with-comments==1.2.2"

    -   id: update-dockerfile
        name: update-dockerfile
        description: 'Update env vars in Dockerfile'
        entry: python -m config.update_dockerfile
        files: ^config/config\.py$
        language: python
        require_serial: true
        additional_dependencies: *jsonc
